apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  name: fluentd-es-conf-{{ include "fluentd.shortReleaseName" . }}
data:
  es.conf: |-
    <system>
      log_level warn
    </system>

    <source>
      @type tail
      path /var/log/containers/provider-console-*_staging_*.log
      pos_file /var/log/fluentd-provider-console.log.pos
      read_from_head true
      tag provider-console
      <parse>
        @type none
      </parse>
    </source>

    <filter **provider-console**>
      @type record_transformer
      <record>
        cluster "console-akash-network"
        pod ${tag}
        namespace "staging"
      </record>
    </filter>

    <match **provider-console**>
      @type elasticsearch
      host "100.70.2.34"  # Elasticsearch server IP
      port 9200
      scheme http  # Change to HTTP since TLS is disabled
      logstash_format true
      logstash_prefix staging-provider-console  # Custom index name
      include_timestamp true
      flush_interval 5s
      request_timeout 30s  # Add timeout setting
    </match>

    <source>
      @type tail
      path /var/log/containers/provider-console-api-*_staging_*.log
      pos_file /var/log/fluentd-provider-console-api.log.pos
      read_from_head true
      tag operator-ip
      <parse>
        @type none
      </parse>
    </source>

    <filter **provider-console-api**>
      @type record_transformer
      <record>
        cluster "console-akash-network"
        pod ${tag}
        namespace "staging"
      </record>
    </filter>

    <match **provider-console-api**>
      @type elasticsearch
      host "100.70.2.34"
      port 9200
      scheme http  # Change to HTTP since TLS is disabled
      logstash_format true
      logstash_prefix staging-provider-console-api
      include_timestamp true
      flush_interval 5s
      request_timeout 30s  # Add timeout setting
    </match>

    <source>
      @type tail
      path /var/log/containers/provider-console-security-*_staging_*.log
      pos_file /var/log/fluentd-provider-console-security.log.pos
      read_from_head true
      tag provider-console-security
      <parse>
        @type none
      </parse>
    </source>

    <filter **provider-console-security**>
      @type record_transformer
      <record>
        cluster "console-akash-network"
        pod ${tag}
        namespace "staging"
      </record>
    </filter>

    <match **provider-console-security**>
      @type elasticsearch
      host "100.70.2.34"
      port 9200
      scheme http
      logstash_format true
      logstash_prefix staging-provider-console-security
      include_timestamp true
      flush_interval 5s
      request_timeout 30s
    </match>