apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  name: fluentd-es-conf-{{ include "fluentd.shortReleaseName" . }}
data:
  es.conf: |-
    <system>
      log_level warn
    </system>

    # Source, Filter, and Match for akash-provider logs
    <source>
      @type tail
      path /var/log/containers/akash-provider-0_akash-services_*.log
      pos_file /var/log/fluentd-akash-provider-0.log.pos
      read_from_head true
      tag akash-provider
      <parse>
        @type none
      </parse>
    </source>

    <filter **akash-provider**>
      @type record_transformer
      <record>
        cluster "a100-mon-obl-akash-pub"
        pod "akash-provider-0"
      </record>
    </filter>

    <match **akash-provider**>
      @type elasticsearch
      host "100.70.2.34"  # Elasticsearch server IP
      port 9200
      scheme http  # Change to HTTP since TLS is disabled
      logstash_format true
      logstash_prefix a100-mon-obl-akash-pub  # Custom index name
      include_timestamp true
      flush_interval 5s
      request_timeout 30s  # Add timeout setting
    </match>

    # Source, Filter, and Match for operator-inventory logs
    <source>
      @type tail
      path /var/log/containers/operator-inventory*.log
      pos_file /var/log/fluentd-operator-inventory.log.pos
      read_from_head true
      tag operator-inventory
      <parse>
        @type none
      </parse>
    </source>

    <filter **operator-inventory**>
      @type record_transformer
      <record>
        cluster "a100-mon-obl-akash-pub"
        pod "operator-inventory"
      </record>
    </filter>

    <match **operator-inventory**>
      @type elasticsearch
      host "100.70.2.34"
      port 9200
      scheme http  # Change to HTTP since TLS is disabled
      logstash_format true
      logstash_prefix a100-mon-obl-akash-pub-operator-inventory  # Custom index name
      include_timestamp true
      flush_interval 5s
      request_timeout 30s  # Add timeout setting
    </match>

    # Source, Filter, and Match for operator-hostname logs
    <source>
      @type tail
      path /var/log/containers/operator-hostname*.log
      pos_file /var/log/fluentd-operator-hostname.log.pos
      read_from_head true
      tag operator-hostname
      <parse>
        @type none
      </parse>
    </source>

    <filter **operator-hostname**>
      @type record_transformer
      <record>
        cluster "a100-mon-obl-akash-pub"
        pod "operator-hostname"
      </record>
    </filter>

    <match **operator-hostname**>
      @type elasticsearch
      host "100.70.2.34"
      port 9200
      scheme http  # Change to HTTP since TLS is disabled
      logstash_format true
      logstash_prefix a100-mon-obl-akash-pub-operator-hostname # Custom index name
      include_timestamp true
      flush_interval 5s
      request_timeout 30s  # Add timeout setting
    </match>

    # Source, Filter, and Match for operator-inventory-hardware-discovery-node logs
    <source>
      @type tail
      path /var/log/containers/operator-inventory-hardware-discovery*.log
      pos_file /var/log/operator-inventory-hardware-discovery.log.pos
      read_from_head true
      tag operator-inventory-hardware-discovery
      <parse>
        @type none
      </parse>
    </source>

    <filter **operator-inventory-hardware-discovery**>
      @type record_transformer
      <record>
        cluster "a100-mon-obl-akash-pub"
        pod "operator-inventory-hardware-discovery"
      </record>
    </filter>

    <match **operator-inventory-hardware-discovery**>
      @type elasticsearch
      host "100.70.2.34"
      port 9200
      scheme http  # Change to HTTP since TLS is disabled
      logstash_format true
      logstash_prefix a100-mon-obl-akash-pub-operator-inventory-hardware-discovery # Custom index name
      include_timestamp true
      flush_interval 5s
      request_timeout 30s  # Add timeout setting
    </match>